#
# List of pre-commit-hooks: https://pre-commit.com/hooks.html
#
# To install as git hook:
#   pre-commit install
#
# To run manually:
#   pre-commit run --all-files
#

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
- repo: git://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
    - id: require-ascii
#    - id: markdownlint
