# https://gohugo.io/getting-started/configuration/#example-configuration
# https://gohugo.io/variables/site/

####
## MARKDOWN

markdown: &markdown
  markup:
    goldmark:
      renderer:
        unsafe: true
    tableOfContents:
      ordered: true

####
## GLOBAL

global_en: &global_en
  baseURL: "https://rynkowski.uk"
  title: "Greg Rynkowski"
  Author: { name: "Greg Rynkowski" }
  params:
    copyright: "Copyright © :YEAR: Greg Rynkowski"
    description: "Greg Rynkowski personal blog"

global_pl: &global_pl
  baseURL: "https://rynkowski.pl"
  title: "Grzegorz Rynkowski"
  Author: { name: "Grzegorz Rynkowski" }
  params:
    copyright: "Copyright © :YEAR: Grzegorz Rynkowski"
    description: "Grzegorz Rynkowski - blog"

####
## MENU anchors

menu_en: &menu_en
  menu:
    main:
      - identifier: "posts"
        name: "posts"
        title: "posts"
        url: "/"
        weight: 10
      - identifier: "about"
        name: "about"
        title: "about"
        url: "/about/"
        weight: 20

menu_pl: &menu_pl
  menu:
    main:
      - identifier: "posts"
        name: "posty"
        title: "posty"
        url: "/"
        weight: 10
      - identifier: "about"
        name: "o mnie"
        title: "o mnie"
        url: "/about/"
        weight: 20

####
## MAIN

languages:
  en:
    weight: 1
    languageName: "English"
    languageCode: "en-gb"
    <<: *global_en
    <<: *menu_en
    baseURL: "https://rynkowski.uk"
    # https://analytics.google.com/analytics/web/#/p257705914
    googleAnalytics: G-59DD9R3DKF
  pl:
    weight: 2
    languageName: "Polski"
    languageCode: "pl"
    <<: *global_pl
    <<: *menu_pl
    baseURL: "https://rynkowski.pl"
    # https://analytics.google.com/analytics/web/#/p257668275
    googleAnalytics: G-15HE1RWC59

<<: *markdown

theme: "etch-greg"
removePathAccents: true

params:
  dark: "auto"
  highlight: true

permalinks:
  # For some of the polish titles, taking title for URL is ok.
  # It is because sometimes title contains polish characters like "ł" and
  # Hugo doesn't transform "ł" to "l".
  # The setting `removePathAccents: true` cares about accents only.
  # In result, for some of the polish posts, I provide slug.
  posts: "/:slug/"

# Disable tags and categories
# https://discourse.gohugo.io/t/i-dont-want-tags-and-categories/12091/4
disableKinds: ["taxonomy", "taxonomyTerm"]

####
## SEO

enableRobotsTXT: true
