baseURL = "https://rynkowski.pl"
languageCode = "en-us"
title = "Greg Rynkowski"
theme = "etch-greg"

[params]
  description = "Greg Rynkowski personal blog."
  copyright = "Copyright © 2020 Greg Rynkowski"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

#  [[menu.main]]
#    identifier = "projects"
#    name = "projects"
#    title = "projects"
#    url = "/projects/"
#    weight = 30

[permalinks]
posts = "/:title/"

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true
